services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: bookstoreappUI
    ports:
      - "5173:80" # Frontend served on port 80 inside the container
    environment:
      - VITE_API_URL=http://bookstoreBackend:4001
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: bookstoreBackend
    restart: always
    ports:
      - "4001:4001"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-backup:/data/db
    networks:
      - mern-network

  nginx-server:
  image: nginx:latest
  container_name: nginx-server
  ports:
    - "80:80"
  depends_on:
    - frontend
    - backend
  networks:
    - mern-network
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./frontend/dist:/usr/share/nginx/html

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-backup:
