version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: bookstoreappui
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-pwa-fullstack_mern-network

  backend:
    build: ./backend
    container_name: bookstorebackend
    restart: always
    ports:
      - "4001:4001"
    environment:
      MONGO_URI: mongodb://localhost:27017/bookStoreApplication?retryWrites=true&w=majority
    depends_on:
      - database
    networks:
      - mern-pwa-fullstack_mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-backup:/data/db
    networks:
      - mern-pwa-fullstack_mern-network

networks:
  mern-pwa-fullstack_mern-network:
    external: true

volumes:
  mongo-backup:
